bitcointracer/apps/bitcoinprice/urls.py
from django.conf.urls import url
from django.urls import path
# from django.contrib import admin
from apps.bitcoinprice import views

app_name='bitcoinprice'

urlpatterns = [
    path('list/', views.BitcoinPriceList.as_view(), name='bitcoinprice-list'),
    path('view/<int:id>/', views.BitcoinPriceDetail.as_view(), name="bitcoinprice-detail"),
    path('create/', views.BitcoinPriceCreate.as_view(), name="bitcoinprice-create"),
    path('edit/<int:id>/', views.BitcoinPriceUpdate.as_view(), name="bitcoinprice-update"),
    path('delete/<int:id>/', views.BitcoinPriceDelete.as_view(), name="bitcoinprice-delete"),
    ]

bitcointracer/apps/home/urls.py
from django.conf.urls import url
from django.urls import path
# from django.contrib import admin
from apps.home import views

app_name='home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('chart/', views.ChartView.as_view(), name="chart"),
    ]

bitcointracer/bitcointracer/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bitcoinprice/', 
    	include("apps.bitcoinprice.urls", 
    		namespace='bitcoinprice')),
    path('', 
    	include("apps.home.urls", 
    		namespace='home')),
]
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bitcointracer/apps/bitcoinprice/models.py
from django.db import models
from datetime import datetime

from django.urls import reverse

# Create your models here.
class BitcoinPrice(models.Model):
	created=models.DateTimeField(auto_now_add=True, null=False)
	date=models.DateField(default=datetime.today, null=False, unique=True)
	value=models.FloatField(null=False, blank=True ,default=None)

	def __str__(self):
		return "%s -> %s" % (self.date, self.value)

	@property
	def BitcoinPrice(self):
		return self.__str__()

	def get_absolute_url(self):
		return reverse('bitcoinprice:bitcoinprice_detail', kwargs={'pk':self.pk})

	class Meta:
		app_label='bitcoinprice'
		verbose_name='Bitcoin Price'
		verbose_name_plural='Bitcoin Prices'
		ordering=('date','value')       

bitcointracer/apps/home/models.py
from django.db import models

# Create your models here.

bitcointracer/apps/bitcoinprice/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from .models import BitcoinPrice
# Create your views here.
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DeleteView

class BitcoinPriceDetail(DetailView):
	model=BitcoinPrice
	pk_url_kwarg = 'id'

class BitcoinPriceList(ListView):
	model=BitcoinPrice
	allow_empty = True 
	ordering = 'date' 
	paginate_by = 50 

class BitcoinPriceCreate(CreateView):
	model=BitcoinPrice
	fields=['date','value']
	pk_url_kwarg = 'id'

class BitcoinPriceUpdate(UpdateView):
	model=BitcoinPrice
	pk_url_kwarg = 'id'
	fields=['date','value']

class BitcoinPriceDelete(DeleteView):
	model=BitcoinPrice
	pk_url_kwarg = 'id'
	success_url=reverse_lazy("home:index")

bitcointracer/apps/home/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView
from apps.bitcoinprice.models import BitcoinPrice
from django.core import serializers

class HomeView(TemplateView):
	template_name = "home/index.html"

class ChartView(TemplateView):
	template_name = "home/chart.html" 

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['bcps'] = BitcoinPrice.objects.all()
		return context

bitcointracer/apps/bitcoinprice/templates/bitcoinprice/bitcoinprice_confirm_delete.html
{% extends "home/index.html" %}
{% load staticfiles %}


{% block extra_css %}

{% endblock %}

{% block content %} 
<div class="ui container">

<h1>Delete Bitcoin Price</h1>
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>
</div>
{% endblock %}


{% block extra_javascript %}

{% endblock %}

bitcointracer/apps/bitcoinprice/templates/bitcoinprice/bitcoinprice_create.html
{% extends "home/index.html" %}

{% load staticfiles %}


{% block extra_css %}

{% endblock %}

{% block content %} 
<div class="ui container">

<h1>Create New Bitcoin Price</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>

</div>
{% endblock %}


{% block extra_javascript %}

{% endblock %}

bitcointracer/apps/bitcoinprice/templates/bitcoinprice/bitcoinprice_detail.html
{% extends "home/index.html" %}

{% load staticfiles %}


{% block extra_css %}

{% endblock %}

{% block content %}
<div class="ui container">
<h1>BitCoin Prices</h1>
 <table style="width:100%">
  <tr>
  	<th>Date Created</th>
    <th>Date</th>
    <th>Price</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <tr>
    <td>{{object.created|date}}</td>
    <td>{{object.date|date}}</td>
    <td>{{object.value|safe}}</td>
    <td><a href="{% url 'bitcoinprice:bitcoinprice-update' id=object.pk %}">Edit</a></td>
    <td><a href="{% url 'bitcoinprice:bitcoinprice-delete' id=object.pk %}">Delete</a></td>
  </tr>
</table> 
</div>
{% endblock %}


{% block extra_javascript %}

{% endblock %}

bitcointracer/apps/bitcoinprice/templates/bitcoinprice/bitcoinprice_form.html
{% extends "home/index.html" %}

{% load staticfiles %}


{% block extra_css %}

{% endblock %}

{% block content %} 
<div class="ui container">

<h1>Update Bitcoin Price</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
</div>
{% endblock %}


{% block extra_javascript %}

{% endblock %}

bitcointracer/apps/bitcoinprice/templates/bitcoinprice/bitcoinprice_list.html
{% extends "home/index.html" %}

{% load staticfiles %}


{% block extra_css %}

{% endblock %}

{% block content %}
<div class="ui container">
<h1>BitCoin Prices</h1>
 <table style="width:100%">
  <tr>
    <th>Date</th>
    <th>Price</th>
    <th>Detail</th>
  </tr> 	
{% for object in object_list %}
     <tr>
    <td>{{object.date|date}}</td>
    <td>{{object.value|safe}}</td>
    <td><a href="{% url 'bitcoinprice:bitcoinprice-detail' id=object.pk %}">View</a></td>
  </tr>
{% empty %}
    <li>There are no Bitcoin Prices yet.</li>
{% endfor %}
</table> 

{% include "paginate.html" %}

</div>
{% endblock %}


{% block extra_javascript %}

{% endblock %}

bitcointracer/apps/home/templates/home/chart.html
{% extends "home/index.html" %}
{% load staticfiles %}


{% block extra_css %}

{% endblock %}

{% block content %} 

<div id="container">

</div>


<script>
	prices=[]
	{% for bc in bcps %}
		new_json={
			id: parseInt("{{bc.id}}"),
			date:new Date("{{bc.date|date:'Y-m-d'}}"),
			value: parseFloat("{{bc.value|safe}}")
		}
		prices.push(new_json)
	{% endfor %}
//let bitcoinprice=JSON.parse("{{bcp_serialized}}");
//console.log(bitcoinprice)

</script>
{% endblock %}


{% block extra_javascript %}
 
<script src="https://code.highcharts.com/stock/highstock.js"></script>
<script src="https://code.highcharts.com/stock/modules/exporting.js"></script>
 <script src="{% static 'js/bitcoin_prices_highcharts.js' %}"></script>

{% endblock %}

bitcointracer/apps/home/templates/home/index.html
{% extends "base.html" %}
{% load staticfiles %}


{% block extra_css %}

{% endblock %}

{% block navbar %} 
<div class="ui container">
<div class="ui four item menu">
  <a class="active item" href="{% url 'home:index' %}">Home</a>
  <a class="item" href="{% url 'bitcoinprice:bitcoinprice-create' %}">Add Price</a>
  <a class="item" href="{% url 'bitcoinprice:bitcoinprice-list' %}">Check List</a>
  <a class="item" href="{% url 'home:chart' %}">Chart
  </a>
</div>

</div>
{% endblock %}

{% block content %} 
<div class="ui container">

</div>
{% endblock %}
{% block extra_javascript %}

{% endblock %}

bitcointracer/files/templates/base.html
{% load staticfiles %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="es"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>
        {% block head_title %}

        {% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">


        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">


        {% block base_css %}
        <link rel="stylesheet" type="text/css" href="{% static "semantic_ui/semantic.min.css" %}">


        {% endblock %}

        {% block extra_css %}

        {% endblock %}


    </head>
    <body>
        {% block navbar %} 
        {% endblock %}
        {% block content %}

        {% endblock %}
   </body>
    <footer>

    {% block base_javascript %}
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "semantic_ui/semantic.min.js" %}"></script>

    {% endblock %}

    {% block extra_javascript %}

    {% endblock %}

    </footer>        

 
</html

bitcointracer/tools/templates/paginate.html
{% if is_paginated %}
<ul class="pagination">
{% if page_obj.has_previous %}
    <li>
        <span><a href="?page={{ page_obj.previous_page_number }}">Previous</a></span>
    </li>
{% endif %}
    <li class="">
        <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
    </li>
{% if page_obj.has_next %}
    <li>
        <span><a href="?page={{ page_obj.next_page_number }}">Next</a></span>
    </li>
{% endif %}
</ul>
{% else %}
    <h3>Is only this...</h3>
{% endif %}